### ISSUE TITLE
[CHORE] Address Mongoose deprecation warnings

### ISSUE THREAD

**Issue by rgroves** [nhcarrigan/christmas-bot#22]
# Chore Request

## Describe the work

As I worked #7 I noticed the following deprecation warnings being thrown by mongoose.

These two when connecting:
- (node:13116) DeprecationWarning: current URL string parser is deprecated, and will be removed in a future version. To use the new parser, pass option { useNewUrlParser: true } to MongoClient.connect.
(Use `node --trace-deprecation ...` to show where the warning was created)

- (node:13116) DeprecationWarning: current Server Discovery and Monitoring engine is deprecated, and will be removed in a future version. To use the new Server Discover and Monitoring engine, pass option { useUnifiedTopology: true } to the MongoClient constructor.

And this one when using `findOneAndUpdate`:
- (node:13116) DeprecationWarning: Mongoose: `findOneAndUpdate()` and `findOneAndDelete()` without the `useFindAndModify` option set to false are deprecated. See: https://mongoosejs.com/docs/deprecations.html#findandmodify

## Additional information

I believe these can be addressed by adding the following global settings before connecting in `index.js`:
```
mongoose.set("useNewUrlParser", true);
mongoose.set("useUnifiedTopology", true);
mongoose.set("useFindAndModify", false);
```

If you'd like I can provide a PR for the update described above.

**Comment by nhcarrigan** [comment]
The options can actually be passed as the second parameter to the `connect` call itself:
```js
mongoose.connect(
  dbString,
  { useFindAndModify: false, useNewUrlParser: true, useUnifiedTopology: true },
  (err) => {
    if (err) {
      console.error(err);
      return;
    }
    console.info("Database connected!");
  }
);
```
