### ISSUE TITLE
[DOC] "CONTRIBUTING.md" issues

### ISSUE THREAD

**Issue by Dboi6339-Soupe** [nhcarrigan/christmas-bot#25]
# Instructions Unclear

**Comment by Dboi6339-Soupe** [comment]
If we are to contribute fully, especially beginners like me, then can this *please* be updated?

Best Wishes,
Soupe.

**Comment by nhcarrigan** [comment]
I just pulled this into repl.it and tested the `npm run build` command. It worked as intended. Can you provide additional information about the error you were having?

**Comment by Dboi6339-Soupe** [comment]
If i follow your instructions exactly up to the `npm run build` part, and I go into Repl.it, it does this:
npm ERR! missing script: build

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/runner/.npm/_logs/2020-11-13T19_08_01_569Z-debug.log



Event though I put exactly: `npm run build`

**Comment by nhcarrigan** [comment]
![image](https://user-images.githubusercontent.com/63889819/99111429-f62be900-25a0-11eb-8352-ab2d3c6f4f7c.png)
Can you confirm that you see this in the `package.json` on your replit?

**Comment by Dboi6339-Soupe** [comment]
No, mine only goes to 30.

**Comment by Dboi6339-Soupe** [comment]
Is there anything I did wrong?

**Comment by nhcarrigan** [comment]
I would try re-generating the repl.it
And make sure that you're basing it off the current version of the app 🙂

**Comment by Dboi6339-Soupe** [comment]
Ok, thanks!

**Comment by Dboi6339-Soupe** [comment]
what do I do for the DB_URI, I have the URI, I just don't know how to identify the <dbname>

**Comment by nhcarrigan** [comment]
For that, you select what you would like the database collection to be named. `ChristmasBot`, for example.

**Comment by Dboi6339-Soupe** [comment]
oh, ok thanks.  Alright now this issue can close.

**Comment by Dboi6339-Soupe** [comment]
I'm sorry, I know I keep re-opening this, but it's the last time I promise.

**Comment by Dboi6339-Soupe** [comment]
I just have an error that I don't know how to deal with
![image](https://user-images.githubusercontent.com/69216104/99201906-1bb42080-2762-11eb-8735-02d946871543.png)

**Comment by Dboi6339-Soupe** [comment]
It says it can't find specific handlers.

**Comment by nhcarrigan** [comment]
You closed the issue again - does that mean you were able to resolve the errors? 🙂
