### ISSUE TITLE
[FEAT] - Add logic for generating random character

### ISSUE THREAD

**Issue by nhcarrigan** [nhcarrigan/christmas-bot#6]
# Feature Request

## Is your feature request related to a problem? Please describe:

Currently the `spawn` embed is hard-coded.

## Describe the solution you'd like

This needs to be refactored to select a random character from the (already imported) `characters.ts` file - the data in the randomly selected `CharacterInt` object can be used to populate the embed. Additionally, add the logic that randomly (with odds) selects the item to award (see notes in code for possible approach?)

**Comment by bjorno43** [comment]
Claiming this as I'm already working on it :P

**Comment by nhcarrigan** [comment]
All yours 😁
