### ISSUE TITLE
[FEAT] - Add database logic for tracking user progress

### ISSUE THREAD

**Issue by nhcarrigan** [nhcarrigan/christmas-bot#7]
# Feature Request

## Is your feature request related to a problem? Please describe:

We will need to add the logic for handling user data.

## Describe the solution you'd like

A function will need to be added in `src/handlers/user.ts`. Should take a parameter of type `User`, and:
* Query the database for a document matching that user (likely saving these by `id`, as that is immutable)
  * If no user found, create new one.
* Confirm the user does NOT have the item won already.
  * If the user DOES, we can return `false`.
* Push the item to the user's inventory, save updated document.
* Return `true` to assist with embed logic.

## Additional context

This cannot be worked on until #4 is complete.

**Comment by rgroves** [comment]
The noted bocker (Issue #4) seems to be addressed. Is this issue still blocked? If not and this is ready to be worked on, I could take it on.

**Comment by nhcarrigan** [comment]
Good to go~!

**Comment by rgroves** [comment]
@nhcarrigan Should what is currently in `src/handlers/user.ts` be moved into `src/data/userSchema.ts`? And then `src/handlers/user.ts` would be the module that would implement all the user model related functionality. I think that is the case but wanted to run it by you first.

**Comment by nhcarrigan** [comment]
I think that's a good approach, yes.
